### ISSUE TITLE
Any chance for a release?

### ISSUE THREAD

**Issue by upsetorandajin** [Petrosz007/goblineer-assistant#1]
Being bad with computers I have no clue how to get this thing working. Could you release a pre-built version for users cause there's definitely interest.

**Comment by Petrosz007** [comment]
You need to download the whole project, install python 3.7 form here: [https://www.python.org/downloads/](https://www.python.org/downloads/)

When you ahve that done, in a console window open the folder (if you are not sure how to do that, cearch for "How to open a folder in cmd").

And there you need to type ``py main.py`` which starts the program. After that, check the Readme for more info.

**Comment by upsetorandajin** [comment]
I managed to get that far but it then stated:

> Traceback (most recent call last):
  File "main.py", line 2, in <module>
    import speech_recognizer as sp
  File "h:\goblineer-assistant-master\speech_recognizer.py", line 5, in <module>
    from pocketsphinx import LiveSpeech
ModuleNotFoundError: No module named 'pocketsphinx'

**Comment by Petrosz007** [comment]
Use this command: `py -m pip install .\pocketsphinx-0.1.3-cp36-cp36m-win_amd64.whl`
It will work on 64bit verions of Windows.
This is the speach recogniser module, this command installs it from the `pocketsphinx-0.1.3-cp36-cp36m-win_amd64.whl` file in the main directory.

**Comment by upsetorandajin** [comment]
Threw out the "pocketsphinx-0.1.3-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform." error, which happened I assume because cp36 indicates it's meant for Python 3.6 and not 3.7.

Edit: Might have to do with the Python I installed, I seem to have installed 32bit instead of 64bit.

**Comment by Petrosz007** [comment]
Try installing Python 3.6 64 bit, see if that works.

**Comment by upsetorandajin** [comment]
I got it to work! Python 3.6.6 64bit, had to pip install some of the dependencies but no biggie! Thanks a lot for your help!
